version: "3.8"

services:
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181 

  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo-db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    container_name: express-mongo
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: "mongodb://root:example@mongo:27017"

  app1:
    container_name: app1
    build: ./app1
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - KAFKA_SERVER=kafka:9092
      - KAFKA_TOPIC=jobs
    depends_on:
      - kafka
      - zookeeper

  app2:
    container_name: app2
    build: ./app2 
    ports:
      - 8083:8083
    environment:
      - PORT=8083
      - KAFKA_SERVER=kafka:9092
      - KAFKA_TOPIC=jobs
    depends_on:
      - kafka

volumes:
  mongo-db: